version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: fabrika_postgres
    environment:
      POSTGRES_DB: fabrika_db
      POSTGRES_USER: fabrika_user
      POSTGRES_PASSWORD: fabrika_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fabrika_network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: fabrika_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fabrika_network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fabrika_backend
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fabrika_db
      DB_USER: fabrika_user
      DB_PASSWORD: fabrika_password
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      WHATSAPP_API_URL: https://api.whatsapp.com
      WHATSAPP_API_TOKEN: your-whatsapp-api-token
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - fabrika_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fabrika_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fabrika_network
    restart: unless-stopped

  # Nginx Load Balancer (optional for production)
  nginx:
    image: nginx:alpine
    container_name: fabrika_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - fabrika_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  fabrika_network:
    driver: bridge